runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /admin.*
  script: main.application
  login: admin

- url: .*
  script: main.application

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"

skip_files:
- .*.pyc
- .git
- .vagrant
- Makefile
- README.md
- Vagrantfile
- provision.sh


